from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO


def generate_pdf(extracted_sections):

    pdf_buffer = BytesIO()

    doc = SimpleDocTemplate(
        pdf_buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()

    story = []

    title = Paragraph(
        """
        <font size="24" color="#023653">
        <b>AI Resume Analysis Report</b>
        </font>
        """,
        styles['Title']
    )

    story.append(title)

    story.append(Spacer(1, 25))

    for heading, content in extracted_sections.items():

        heading_para = Paragraph(
            f"""
            <font size="16" color="#056C89">
            <b>{heading}</b>
            </font>
            """,
            styles['Heading2']
        )

        content_para = Paragraph(
            f"""
            <font size="12">
            {content.replace(chr(10), "<br/>")}
            </font>
            """,
            styles['BodyText']
        )

        story.append(heading_para)
        story.append(Spacer(1, 8))
        story.append(content_para)
        story.append(Spacer(1, 18))

    footer = Paragraph(
        """
        <font size="10" color="grey">
        Generated by Aldrin's AI Resume Analyzer
        </font>
        """,
        styles['BodyText']
    )

    story.append(Spacer(1, 25))
    story.append(footer)

    doc.build(story)

    pdf_buffer.seek(0)

    return pdf_buffer

    